# Generated by Django 3.1.7 on 2021-03-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BombDefused',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.IntegerField()),
                ('event_number', models.IntegerField()),
                ('round', models.IntegerField()),
            ],
            options={
                'db_table': 'bomb_defused',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BombPlanted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.IntegerField()),
                ('event_number', models.IntegerField()),
                ('round', models.IntegerField()),
            ],
            options={
                'db_table': 'bomb_planted',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'event_json',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_code', models.TextField(unique=True)),
                ('match_time', models.DateTimeField()),
                ('match_duration', models.IntegerField()),
            ],
            options={
                'db_table': 'game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('weapon_name', models.TextField()),
                ('item_name', models.TextField()),
                ('alternate', models.BooleanField()),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemEquip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_number', models.IntegerField()),
                ('round', models.IntegerField()),
            ],
            options={
                'db_table': 'item_equip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemTypeL',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'item_type_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapL',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('map_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'map_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuid', models.TextField()),
                ('player_name', models.TextField()),
            ],
            options={
                'db_table': 'player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerBlind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blind_duration', models.FloatField()),
                ('event_number', models.IntegerField()),
                ('round', models.IntegerField()),
            ],
            options={
                'db_table': 'player_blind',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerDeath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistedflash', models.BooleanField()),
                ('headshot', models.BooleanField()),
                ('dominated', models.BooleanField()),
                ('revenge', models.BooleanField()),
                ('wipe', models.BooleanField()),
                ('penetrated', models.BooleanField()),
                ('noscope', models.BooleanField()),
                ('thrusmoke', models.BooleanField()),
                ('attackerblind', models.BooleanField()),
                ('distance', models.FloatField(blank=True, null=True)),
                ('event_number', models.IntegerField()),
                ('round', models.IntegerField()),
            ],
            options={
                'db_table': 'player_death',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerFalldamage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.FloatField()),
                ('event_number', models.IntegerField()),
                ('round', models.IntegerField()),
            ],
            options={
                'db_table': 'player_falldamage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerHurt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('dmg_health', models.IntegerField()),
                ('dmg_armor', models.IntegerField()),
                ('hitgroup', models.IntegerField()),
                ('event_number', models.IntegerField()),
                ('round', models.IntegerField()),
            ],
            options={
                'db_table': 'player_hurt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoundEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.IntegerField()),
                ('message', models.TextField()),
                ('event_number', models.IntegerField()),
                ('round', models.IntegerField()),
            ],
            options={
                'db_table': 'round_end',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoundMvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.IntegerField()),
                ('event_number', models.IntegerField()),
                ('round', models.IntegerField()),
            ],
            options={
                'db_table': 'round_mvp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoundStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timelimit', models.IntegerField()),
                ('event_number', models.IntegerField()),
                ('round', models.IntegerField()),
            ],
            options={
                'db_table': 'round_start',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamL',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'team_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponFire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silenced', models.BooleanField()),
                ('event_number', models.IntegerField()),
                ('round', models.IntegerField()),
            ],
            options={
                'db_table': 'weapon_fire',
                'managed': False,
            },
        ),
    ]
